version: '3.5'

services:
  freegpt-neurogen:
    image: freegpt-neurogen
    container_name: freegpt-neurogen
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1338:1338"
      - "1337:1337"
